services:
  minio:
    image: minio/minio
    container_name: parking-minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    volumes:
      - ./s3:/data

  mailhog:
    image: mailhog/mailhog
    container_name: parking-mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
